### ISSUE TITLE
Run node -c on package.json

### ISSUE THREAD

**Issue by nouex** [reecehudson/node-emitter-details#32]

**Comment by nouex** [comment]
If you run `node -c package.json` on :

``` json
{
 "hey": "there"
}
```

console output is:

```
  "hey": "there"
       ^

SyntaxError: Unexpected token :
    at startup (node.js:113:11)
    at node.js:968:3
```

This is totally valid.  It doesn't error if the quote marks are omitted from the prop name.  Should this be a node issue???

Well, closing for now as this is not possible.
